An $N$-player normal form game consists of strategy spaces for each player, and a payoff function.

In [1]:
import nashpy as nash

In [2]:
A = [[3, 1], [0, 2]]
B = [[2, 1], [0, 3]]

battle_of_the_sexes = nash.Game(A, B)
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

The prisoners dilemma is probably the most famous of all game examples. In this game, two thieves are under investigation by police. If both cooperate and don't reveal information, they get a short sentence. If one betrays the other, they get a deal while the other thief gets a long sentence. If they both reveal information, they get a middle length sentence.

In [3]:
A = [[3, 0], [5, 1]]
B = [[3, 5], [0, 1]]

prisoners_dilemma = nash.Game(A, B)
prisoners_dilemma

Bi matrix game with payoff matrices:

Row player:
[[3 0]
 [5 1]]

Column player:
[[3 5]
 [0 1]]

A **zero-sum game** is one in which the payoff matrices satisfy $A=-B$.

An example is a coin matching game. Players can choose to show their coin heads or tails. If both players show the same face, player 1 wins, otherwise player 2 wins.

In [5]:
A = [[1, -1], [-1, 1]]
B = [[-1, 1], [1, -1]]

coin_matching = nash.Game(A, B)
coin_matching

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

Lets begin trying to implement this in our own classes.

In [24]:
import numpy as np

class game:
    """
    2 player normal form game
    """
    def __init__(self, payoff_A, payoff_B):
        self.payoff_A = np.array(payoff_A)
        self.payoff_B = np.array(payoff_B)
        
    def __repr__(self):
        return "player 1 payoff:\n" + str(self.payoff_A) + "\n\n" + \
               "player 2 payoff:\n" + str(self.payoff_B)

In [25]:
A = [[3, 0], [5, 1]]
B = [[3, 5], [0, 1]]

prison = game(A, B)
prison

player 1 payoff:
[[3 0]
 [5 1]]

player 2 payoff:
[[3 5]
 [0 1]]