In [1]:
import numpy as np
import nashpy as nash

Let $(A,B)$ be a given 2-player normal form game. We want to have a notion of declaring a strategy is *better* than another strategy.

We say strategy $s$ is **dominated** by strategy $\bar{s}$ if for all strategies $t$ of the other player,
$$ u(s,t) < u(\bar{s},t) $$

In [3]:
A = [[3, 0], [5, 1]]
B = [[3, 5], [0, 1]]

pdil = nash.Game(A, B)
pdil

Bi matrix game with payoff matrices:

Row player:
[[3 0]
 [5 1]]

Column player:
[[3 5]
 [0 1]]

In the above case of the prisoners dilemma, we see that for player 1, the second row is a dominating strategy, and likewise for player 2, the second column is a dominating strategy.

But what about games like this?

In [4]:
A = [[3, 0], [3, 1]]
B = [[3, 3], [0, 1]]

pdil_weak = nash.Game(A, B)
pdil_weak

Bi matrix game with payoff matrices:

Row player:
[[3 0]
 [3 1]]

Column player:
[[3 3]
 [0 1]]

In this case, the second row/column is still a better strategy, but it no longer strongly dominates. We should have a weaker notion, called **weakly dominating**.

We say strategy $s$ is **weakly dominated** by strategy $\bar{s}$ if for all strategies $t$ of the other player,
$$ u(s,t) \le u(\bar{s},t) $$ and there exists a $t'$ so that $$ u(s,t') < u(\bar{s},t') $$

Finally, we say that players are **rational** if they play games via ignoring weakly dominated strategies.